# Generated by Django 6.0.6 on 2026-06-29 15:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0002_remove_usuario_placa_remove_usuario_tipovehiculo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeTurno',
            fields=[
                ('id_informe', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora_inicio', models.DateTimeField(help_text='Inicio de la jornada laboral del vigilante')),
                ('fecha_hora_fin', models.DateTimeField(default=django.utils.timezone.now, help_text='Cierre de turno')),
                ('total_entradas', models.IntegerField(default=0)),
                ('total_salidas', models.IntegerField(default=0)),
                ('vehiculos_quedados', models.IntegerField(default=0, help_text='Vehículos que no salieron al terminar el turno')),
                ('novedades_observaciones', models.TextField(blank=True, help_text='Reporte escrito de incidentes ocurridos', null=True)),
                ('entrega_sin_novedad', models.BooleanField(default=True)),
                ('vigilante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes_turno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'informes_turno',
                'ordering': ['-fecha_hora_fin'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id_registro', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='accesos.vehiculo')),
                ('vigilante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registros_acceso',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
