# Generated by Django 6.0.6 on 2026-08-26 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0002_usuario_ficha'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacceso',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mis_accesos', to=settings.AUTH_USER_MODEL),
        ),
    ]
