# Generated by Django 6.0.6 on 2026-06-29 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0003_informeturno_registroacceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacceso',
            name='motivo_apertura',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='nombre_conductor_manual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='placa_manual',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='tipo_vehiculo_manual',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registroacceso',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('APERTURA_MANUAL', 'Apertura Manual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registroacceso',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='accesos.vehiculo'),
        ),
    ]
